### ISSUE TITLE
Apply Swift 3 API Guidelines

### ISSUE THREAD

**Issue by zwaldowski** [bignerdranch/Deferred#101]
Bikeshed time. See also #20, #21, and #66.

Are you a BNR person assigned to this issue? You've been assigned for review! You don't need to do anything other than read through this issue and leave feedback.

This document refers to the Swift 3-style name of types unless explicitly referring to the old API.

### Proposed changes

<details>
* `Deferred.init(value:)` ➡️ `Deferred.init(filledWith:)`
* `ExecutorType` ➡️ `Executor`
* `ExecutorType.submit(_:)` ➡️ `Executor.async(_:)`
* `Sequence<FutureType>.earliestFilled` ➡️ `Sequence<FutureProtocol>.firstCompleted()`
* `Collection<FutureType>.joinedValues` ➡️ `Collection<FutureProtocol>.allCompleted()`
* `FutureType` ➡️ `FutureProtocol`
* `FutureType.wait(_:)` ➡️ `FutureProtocol.wait(until:)`
* `FutureType.Type.genericQueue` ➡️ `DispatchQueue.Type.any()` (i.e., `upon(.any()) { ... }`)
* `FutureType.uponMainQueue(_:)` ➡️ removed (use `upon(.main)`)
* `FutureType.upon(:_:)` ➡️ `FutureType.upon(_:execute:)`
* `FutureType.map(upon:_:)` ➡️ `FutureType.map(upon:transform:)`
* `FutureType.flatMap(upon:_:)` ➡️ `FutureType.andThen(upon:start:)`
* `IgnoringFuture` ➡️ remove (#75)
* `LockProtected<T>` ➡️ `Protected<Value>`
* `PromiseType` ➡️ `PromiseProtocol`
* `PromiseType.fill(_:)` ➡️ `PromiseProtocol.fill(with:)`
* `PromiseType.fill(_:assertIfFilled:file:line:)` ➡️ `PromiseProtocol.mustFill(with:)`
* `ReadWriteLock` ➡️ `Locking`
* `Timeout` ➡️ removed, use Dispatch timeouts

#### Task
* introducing ➡️ `Task.init(executing:upon:)`
* `Task.init(upon:per:onCancel:body:)` ➡️ `Task.init(executedUpon:per:cancellingWith:body:)`
* `IgnoringTask` ➡️ removed (see also #75)
* `PromiseType<ResultType>.succeed(_:)` ➡️ `PromiseProtocol<ResultProtocol>.succeed(with:)`
* `PromiseType<ResultType>.fail(_:)` ➡️ `PromiseProtocol<ResultProtocol>.fail(with:)`
* `PromiseType<ResultType>.fill(with:)` ➡️ removed
* `TaskAccumulator` ➡️ `TaskGroup`
* `TaskAccumulator.accumulate(_:)` ➡️ `TaskGroup.include(_:)`
* `TaskAccumulator.allCompleted()` ➡️ `TaskGroup.completed()`
* `Collection<TaskType>.joinedTasks` ➡️ `Collection<TaskProtocol>.allSucceeded()`
* `FutureType<ResultType>.recover(upon:_:)` ➡️ `FutureProtocol<ResultProtocol>.recover(upon:substituting:)`
* `TaskResult.Success` ➡️ `TaskResult.success`
* `TaskResult.Failure` ➡️ `TaskResult.failure`
* `ResultType` ➡️ `Either`
* introducing ➡️ `Either.Left` (`associatedtype Left = Error`)
* `ResultType.Value` ➡️ `Either.Right`
* `ResultType.withValues(ifSuccess:ifFailure:)` ➡️ `Either.withValues(left:right:)`
* `ResultType.init(value:)` ➡️ removed
* `ResultType.extract()` ➡️ `ResultProtocol.extracted()`
</details>

### Places for improvement/undecided

<details>

- [x] Collection tactics

* `Sequence<FutureProtocol>.firstCompleted()`
* `Collection<FutureProtocol>.allCompleted()`
* `TaskGroup. completed()`
* `Collection<TaskProtocol>.allSucceeded()`

- [x] Function body parameter external names

We currently lean towards unnamed function body parameters. In practice, both discussing these methods and using them is confusing.

* Swift 3's `Dispatch` uses `execute`.
* Should we have unique body names for all variants (`upon`, `map`, `flatMap`, `recover`), or just one?
* Swift 3 also does away with body parameter names in a couple of places, notably `reduce`.

[Read more](https://github.com/bignerdranch/Deferred/issues/101#issuecomment-244812246).

These don't feel similar, even though they are.

- [x] `FutureProtocol.Value`, `PromiseProtocol.Value`, `Protected<Value>`

The names of these associated types or generic placeholders are wimpy. In the `Task` code in particular, they lead to nesting like `where Future.Value.Value: Foo`.

- [x] `TaskResult` And friends

[See also](https://github.com/bignerdranch/Deferred/issues/101#issuecomment-235913682) and [more](https://github.com/bignerdranch/Deferred/issues/101#issuecomment-238425418).

- [x] Defaulted `upon` parameters

The current pattern of `upon` arguments falling back to a default queue has led to some confusion, and contributes to code duplication (see above). Do we just do away with it?

@jgallagher votes to axe it. @zwaldowski is mixed.

We might be able to split the difference and relegate the current behavior to an extension `DispatchQueue.Type.any`, a la `future.upon(.any) { … }`

Removing this would ameliorate the code duplication concerns above.

- [x] `FutureProtocol.peek()`, `FutureProtocol.value`

I personally don't like them. They're already test-only.

- [x] `FutureProtocol.wait(until:)`

`FutureProtocol.wait(until:)`, like sane people, or `FutureProtocol.wait(deadline:)`, like `DispatchQueue.asyncAfter(deadline:execute:)`?

- [x] `FutureProtocol.andThen(upon:start:)` (#21)

* Old name is `flatMap(upon:_:)` to match stdlib.
* Rust uses `andThen`.
* Scala uses `bind` (as did Deferred 1.0).
* `flatMap` is confusing for many users.

- [x] `preconditionFilled(with:)`

See discussion in #105.

</details>

**Comment by zwaldowski** [comment]
[SE-0133](https://github.com/apple/swift-evolution/blob/master/proposals/0133-rename-flatten-to-joined.md)'s acceptance should help drive our understanding. I'll update the impact on Deferred accordingly.

**Comment by zwaldowski** [comment]
Updated with my feels.

**Comment by jeremy-w** [comment]
The `ResultProtocol` protocol name got bumped to include `Protocol` due to `Result` the enum.

It might be possible to give the protocol its own unique name along the lines of `Try` [as used in Scala.](http://www.scala-lang.org/api/2.11.8/index.html#scala.util.Try)

**Comment by zwaldowski** [comment]
`FutureProtocol.wait(until:)` or `FutureProtocol.wait(deadline:)`, like `DispatchQueue.asyncAfter(deadline:execute:)`?

**Comment by zwaldowski** [comment]
@jeremy-w: What do you envision the enum cases be for `Try`? Its use changes up the tense a little; maybe `Try.returned(Value)`, `Try.thrown(ErrorType)`?

My current thinking is that `ResultProtocol` becomes `Either`, with `associatedtype Left = ErrorType` and `withValues(left:right:)`. I think this presents a much better interface overall. Still left a little confused with the enum proper, though.

**Comment by jeremy-w** [comment]
Scala used `success`/`failure` with `Try`. Not sure how much that is worth though.

I'd need to see some typical code using these to be able to work over the names properly. Do you have an example that you could share?

**Comment by zwaldowski** [comment]
That's in part tricky, as with `Task` we strive to make the `Result` bits as hidden as possible (`PromiseProtocol.succeed(with:)`, etc.), but here's a boilerplate-a-riffic example:

```swift
let request = ...
let deferred = ...

webService.perform(request).upon { result in
    switch result {
    case .success(let response):
        do {
            let values = try dataParser.parseFromJson(response.data)
            deferred.fill(.success(values))
        } catch {
            print("error occurred: \(error)")
            deferred.fill(.failure(.invalidResponse))
        }
    case .failure(let error):
        print("error occurred: \(error)")
        deferred.fill(.failure(.requestFailed(error)))
    }
}

return Future(deferred)
```

**Comment by jgallagher** [comment]
> The current pattern of upon arguments falling back to a default queue has led to some confusion. Do we just do away with it?

I vote yes. I think this was a mistake on my part. I was trying to keep call sites more succinct in the common case, but now that specifying queues _is_ more succinct, that's an even weaker reason.

**Comment by jgallagher** [comment]
I'm a little scared to open this can of worms, but can you talk through why you want `Either` with left/right instead of `ResultProtocol` with success/failure? I've never been a big fan of `Either` for success/failure use cases, and this seems compounded if our concrete type does use Result-like naming.

**Comment by zwaldowski** [comment]
No worms to be had; I'm not the world's biggest fan of the `Either` terminology. @jeremy-w felt (and I agreed) that `TaskResult` and `TaskResultProtocol` are confusing.

We're stuck trying to balance three things with the `Result` stuff:

- We can't use the common-case `Result` naming.
- We need a protocol side for protocol extensions, with a bare minimum of functionality.
- We don't want the protocol and concrete type to be confused.

Since the protocol requirements are only `init` and `withValues`, I feel `Either` strikes a good balance and hierarchy, and marks whatever we name `Result` as as the clear preference, while still giving a powerful implementation to `Task`.

**Comment by jgallagher** [comment]
I feel like `TaskResult` / `TaskResultProtocol` paralleled nicely with `Task` / `TaskProtocol`, but switching to `TaskResult` / `Either` breaks that. I haven't spent a ton of time reading over the Task PR, but my impression is that the protocols are there for very advanced users / use cases and are likely to be rarely used directly outside of our library. If that's true, I don't _think_ confusion over the names of the protocols is a great concern, since the folks apt to be confused will only be using the concrete types anyway.

**Comment by zwaldowski** [comment]
We were workshopping a change to `TaskResult` as well

That's not an incorrect reading of the intent of #98; my intent is for it to be an implementation detail (except for in the ways it can't be, of course). That said, you *will* run into `TaskResult`, and I want to avoid people's noses crinkling when they do. Your point is taken, though.

**Comment by zwaldowski** [comment]
FWIW I need to see if `TaskProtocol` is even necessary under Swift 3. If I can make `cancel` propagation happen without it, then `Task` can just be concrete.

**Comment by zwaldowski** [comment]
Re: [this](https://github.com/bignerdranch/Deferred/issues/101#issuecomment-238881823), honestly, maybe we should just try a downcast to `Task`.

**Comment by zwaldowski** [comment]
Updated with `andThen` (#21) and our current thinking on function body parameters.

**Comment by zwaldowski** [comment]
Based on #111, it looks like we'll be able to remove `TaskType`, if that affects the understanding of the `Task` / `TaskResult` / `TaskResultType` trinity.

**Comment by rcedwards** [comment]
Overall looks very nice to me. Just a few thoughts.

1. I too would prefer `Result` with `.success` and `.failure` rather than using `Either`.

2. `PromiseType.fill(_:assertIfFilled:file:line:) ➡️ PromiseProtocol.preconditionFilled(with:)`
So I'm assuming the `.preconditionFilled` would be replacing the case to assert when the deferred has already been filled? B/c to me this reads a little confusing and sounds like the deferred already being filled is the pre-conditions.

3. `TaskAccumulator.accumulate(_:) ➡️ TaskGroup.include(_:)`
Could we model this after the `ResultType` below and have the signature be `TaskGroup.with(tasks:)`?

**Comment by zwaldowski** [comment]
@rcedwards:

1. `TaskResult.success` and `TaskResult.failure` are what we currently have for concrete use with `Task`, the bits about `Either` are for the protocol we need to represent this work. (To @jgallagher's point, this is clearly confusing).

2. OK, I have to reconsider. It seems like the conversation we had about it before got lost, but that was mentioned before.

3. Is `Collection<TaskProtocol>.completed()` what you're describing there? `TaskAccumulator` has a different usage model where you build up things over time.

**Comment by zwaldowski** [comment]
@rcedwards: Oh, duh, `preconditionFilled` is talked about in #105.

**Comment by davidahouse** [comment]
@zwaldowski have we considered just having `fill` throw instead of the `preconditionFilled`? I get that filling twice is programmer error, but throwing would be slightly less harsh, while giving the option of dealing with this happening in a sane manner other than crashing. By throwing, we are giving the signal that `this can fail!` while not being so prescriptive of what happens. And developers can still do `try!` if they are sure this isn't going to happen. Possibly not a good name, but perhaps we have two methods `fill` and `tryFill`?

**Comment by zwaldowski** [comment]
@davidahouse We did consider it. It was far too burdensome to use.

**Comment by zwaldowski** [comment]
I noticed Swift 3 removes external names for body parameters in a couple of places (like `reduce`), which gives us more to think about. I've noted that in the appropriate section above.

**Comment by jeremy-w** [comment]
@zwaldowski Could you expand on what you wrote about the body params issue?

- What's a "function body parameter"? Is this just a parameter of function type?
- Am I correct in understanding the primary problem perceived is difficulty in discussing some methods, which leads to difficulty using them?
- Could you provide an example of some methods and the sort of problem that arises to make this discussion more concrete?

**Comment by zwaldowski** [comment]
Sure. Consider the stdlib's "functional callbacks":

```swift
let allFriends1 = users.flatMap { $0.friends }

func friends(of user: User) -> [User] { … }
let allFriends2 = users.flatMap(friends)
```

In Swift 3, these are tied together by a consistent thread: the body parameters have no external names. The body parameter is not a side-effect, or input; it *is* the `flatMap`, etc.

```swift
let sum = grades.reduce(0.0, +)
```

In trying to keep the same pattern for Deferred, we end up unlabelling the body parameter even when it would make sense to have one, making it difficult to refer to the method and awkward at the call site:

```swift
let laterFriends = fetchUsers().flatMap(upon: myAwesomeQueue, fetchFriends)
```

But this isn't a universal pattern. Imported and audited Cocoa APIs as well as the redesigned Dispatch API have external names like `completion`, `handler`, and `execute`. So, is this because those methods are asynchronous (i.e., `@escaping`) or what?

So, it mostly comes down to understanding the use model for our callback-taking functions, as in #21. Are these "functional callbacks"?

```swift
let a = one.upon(fn)
let b = two.map(upon: context, fn)
let c = three.flatMap(upon: queue, doMoreWithResult)
let d = task.recover(upon: foo, emptyUsersArray)
```

Or "Dispatch callbacks"? (Seen here with straw-man unique names.)

```swift
let a = one.upon(queue, execute: fn)
let b = two.map(upon: queue, transform: fn)
let c = three.andThen(upon: queue, start: doMoreWithResult)
let d = task.recover(upon: queue, provider: emptyUsersArray)
```

**Comment by zwaldowski** [comment]
For `upon`, I'm going to split the difference: `map`, `andThen`, and `recover` will lose the default `upon` parameter, but `upon` will keep the any-old-Dispatch-queue default.

**Comment by zwaldowski** [comment]
I'm punting on `FutureProtocol.Value`, `PromiseProtocol.Value`, and `Protected<Value>` (i.e., `Value`). Please somebody comment if they have an idea.

**Comment by zwaldowski** [comment]
I'm locking down callback names for now:

* `upon(_:execute:)`
* `map(upon:transform:)`
* `andThen(upon:start:)`
* `recover(upon:execute:)`

Please let me know if you have alternatives, particularly for `recover`.

**Comment by zwaldowski** [comment]
I've made another pass at the collection methods:

* `Sequence<FutureProtocol>.firstCompleted()`
* `Collection<FutureProtocol>.allCompleted()`
* `TaskGroup.completed()`
* `Collection<TaskProtocol>.allSucceeded()`

**Comment by jeremy-w** [comment]
Recover ideas:

- `recover(upon:with:)`
- `recover(upon:bySubstituting:)`
- `recover(upon:substitution:)`
- `recover(upon:per:)`
- `recover(upon:as:)`

(The `transform` param name with `map` doesn't fit my mental model of mapping well, but it's what the stdlib is using, so too bad for me - agreeing with the stdlib takes precedence.)

**Comment by zwaldowski** [comment]
Hm, I like the `substitution` path. I wonder if it should be just `substituting`.

I don't disagree on `map`  We're willing the break with the stdlib where it makes sense; is there something that'd fit your model better?

**Comment by jeremy-w** [comment]
`recover(upon:substituting:)` sounds good to me. :+1:

The map naming is tricky. I think of the function itself as the mapping. So it'd be `map(upon:map:)` or `map(upon:mapping:)` or `map(upon:by:)`, or maybe `map(upon:taking:)`. That last one comes from informal language like "this takes `x` to `y`" or "this sends `x` to `y`".
